name: iOS starter workflow

on:
  push:
    branches: [ "master" , "feature/automation"]
  pull_request:
    branches: [ "master", "feature/automation"]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pod Install
        run: pod install
        
